#version 440 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform float factor;

layout(binding = 0, r32f) readonly uniform image1D a;
layout(binding = 1, r32f) readonly uniform image1D b;
layout(binding = 2, r32f) readonly uniform image1D c;
layout(binding = 3, r32f) writeonly uniform image1D d;

void main()
{
  int id = int(gl_GlobalInvocationID.x);
  imageStore(d, id, (imageLoad(a, id).x*imageLoad(c, 0).x*factor + imageLoad(b, id).x).xxxx)
}
